### PR TITLE
Get all of Stephen's Templates and Ctrls and Services into the Master.

### PR DESCRIPTION
**Pull request by scottwo**
Please!

### CODE REVIEW

**Comment by gabemeola** [comment]
looks good to me. Merging.

**Comment by jordangunther** [comment]
I created a pull request, were you guys notified? Can do you have access to
merge?

Thank You,

Jordan Gunther

(801)-616-7897

369 E 1165 N

Orem, UT 84057

jordankgunther@gmail.com

**Comment by gabemeola** [comment]
Yeah I already merged it. It looked good

**Comment by gabemeola** [comment]
Oh I merged the last one opened he Scott not the most recent one.

**Pull request merged**
